#!/bin/bash

set -e

source scripts/activate-graal

rm -rf classes && mkdir classes
echo "Building uberjar"
clojure -X:depstar


# echo "Generating reflection information"
# mkdir -p resource/META-INF/native-image
# LD_LIBRARY_PATH="$(pwd)/graalvm/lib" java -agentlib:native-image-agent=config-output-dir=META-INF/native-image -jar target/ds-graal-uber.jar

    # -J--add-modules -Jjdk.incubator.foreign \
    # -J-Dforeign.restricted=permit -J--add-opens \
    # -Jjava.base/java.lang=ALL-UNNAMED \

graalvm/bin/native-image \
    --report-unsupported-elements-at-runtime \
    --initialize-at-build-time \
    --no-fallback \
    --no-server \
    -H:+ReportExceptionStackTraces \
    --allow-incomplete-classpath \
    --initialize-at-run-time=org.apache.hadoop.util.DataChecksum$Java9Crc32CFactory \
    --initialize-at-run-time=org.apache.hadoop.io.erasurecode.rawcoder.NativeRSRawDecoder \
    --initialize-at-run-time=org.apache.hadoop.io.erasurecode.rawcoder.NativeRSRawEncoder \
    --initialize-at-run-time=org.apache.hadoop.io.erasurecode.rawcoder.NativeXORRawEncoder \
    --initialize-at-run-time=org.apache.hadoop.io.erasurecode.rawcoder.NativeXORRawDecoder \
    -J-Dclojure.spec.skip-macros=true \
    -J-Dclojure.compiler.direct-linking=true \
    -J-Dtech.v3.datatype.graal-native=true \
    -jar target/ds-graal-uber.jar ds-graal
